apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    type: local
  name: pv-volume-jira-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pv-claim-jira-data
    namespace: jira-stack
  nfs:
    path: /gpfsshare/BS/jira-data
    server: gpfsdev.homolog.ibm.cloud
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jira-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-jira-data
  namespace: jira-stack
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: jira-data
  volumeName: pv-volume-jira-data
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi