apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    type: local
  name: pv-volume-jira-shared
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pv-claim-jira-shared
    namespace: jira-stack
  hostPath:
    path: /mnt/jira
  storageClassName: jira-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-jira-shared
  namespace: jira-stack
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: jira-shared
  volumeName: pv-volume-jira-shared
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi