CREATE USER user_jira;
ALTER USER user_jira WITH PASSWORD 'pass_jira';
CREATE DATABASE jiradb WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE jiradb TO user_jira;